"""Parity tests for the 七政四余 政余格局 (guolaoMoira) engine.

``tests/fixtures/guolao_moira_oracle.json`` was generated by running horosa's own
``guolaoMoira.js`` (``buildLocalMoiraPatterns``) on synthetic charts with empty
``godRows`` and empty ``fixedStarSu28`` — i.e. exactly horosa's *offline* behaviour,
where the 神煞-dependent patterns (日月拱贵人/命登岁驾) and 近宿界 do not fire. The
FateBridge port must reproduce the pattern list (name + level, in order) byte-for-byte
for every case. Pure sign-index arithmetic → deterministic across Python 3.10–3.13.
"""

from __future__ import annotations

import json
from pathlib import Path

from fatebridge.core import guolao_moira

_FIXTURE = Path(__file__).resolve().parent / "fixtures" / "guolao_moira_oracle.json"
_CASES = json.loads(_FIXTURE.read_text(encoding="utf-8"))


def _names_levels(patterns):
    return [(p["name"], p["level"]) for p in patterns]


def test_oracle_fixture_is_nonempty():
    assert _CASES, "guolaoMoira oracle fixture must contain cases"


def test_matches_horosa_js_oracle():
    """Every case must match horosa's guolaoMoira.js pattern list exactly."""
    for case in _CASES:
        got = _names_levels(guolao_moira.calculate(case["facts"]))
        expected = [(p["name"], p["level"]) for p in case["expected"]]
        assert (
            got == expected
        ), f"mismatch on case: {case['label']}\n  got={got}\n  exp={expected}"


def test_good_patterns_sort_before_bad():
    """build order: good first, bad after (matches JS level sort)."""
    for case in _CASES:
        patterns = guolao_moira.calculate(case["facts"])
        ranks = [0 if p["level"] == "good" else 1 for p in patterns]
        assert ranks == sorted(ranks), case["label"]


def test_god_dependent_patterns_inert_without_gods():
    """日月拱贵人 / 命登岁驾 require 神煞 (not supplied in Phase 1) → never fire."""
    for case in _CASES:
        names = {p["name"] for p in guolao_moira.calculate(case["facts"])}
        assert "日月拱贵人" not in names
        assert "命登岁驾" not in names


def test_section_text_format():
    """build_section_text mirrors runGuolaoMoira: 喜格/忌格 lines, 名（detail）；-joined."""
    # multi-fire case is index 0
    patterns = guolao_moira.calculate(_CASES[0]["facts"])
    text = guolao_moira.build_section_text(patterns)
    lines = text.split("\n")
    assert lines[0].startswith("喜格：")
    assert lines[1].startswith("忌格：")
    assert "金水相涵" in lines[0]
    assert "孛犯太阳" in lines[1]
    assert "；" in lines[1]  # multiple 忌格 joined


def test_empty_chart_yields_no_patterns():
    """A chart with no usable positions produces empty 喜格/忌格 (not a crash)."""
    patterns = guolao_moira.calculate({"asc_lon": None, "planet_signidx": {}})
    assert patterns == []
    assert guolao_moira.build_section_text(patterns) == "喜格：（无）\n忌格：（无）"
