"""Regression lock: FateBridge's 太乙 命法 port must match kintaiyi byte-for-byte.

The fixtures in ``tests/fixtures/taiyi_kintaiyi_fixtures.json`` were generated by
driving the reference implementation ``kintaiyi`` (kentang2017, MIT) at its
``Taiyi(...).taiyi_life`` ji_style=0 markers for 14 diverse datetimes (spanning
节气 boundaries, 阳遁/阴遁, both sexes, the 1900 epoch anchor, and edge years).
kintaiyi is intentionally NOT a FateBridge dependency — the reference values are
baked into the committed fixture file.

Each fixture carries kintaiyi's OWN four 干支 pillars and lunar year, so this test
proves the *transform* (pillars + lunar year → board markers) is faithful,
independent of which calendar engine produced the pillars.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from fatebridge.core.metaphysics.taiyi import (
    _baliu,
    _bigyo,
    _eightwind,
    _fivewind,
    _flybird,
    _kingfu,
    _smyo,
    _taijun,
    _TaiyiLife,
    _threewind,
    _wufu,
    _yangjiu,
)

_FIXTURES = json.loads(
    (Path(__file__).parent / "fixtures" / "taiyi_kintaiyi_fixtures.json").read_text(
        encoding="utf-8"
    )
)


@pytest.mark.parametrize("fixture", _FIXTURES, ids=[str(f["input"]) for f in _FIXTURES])
def test_taiyi_life_markers_match_kintaiyi(fixture):
    gz = fixture["gangzhi"]
    lunar_year = fixture["lunar"]["年"]
    engine = _TaiyiLife(gz[0], gz[1], gz[2], gz[3], lunar_year)
    acc = engine.accnum()

    assert acc == fixture["accnum"]
    kook = engine.kook()
    assert kook["文"] == fixture["kook_wen"]
    assert kook["數"] == fixture["kook_num"]
    assert kook["年"] == fixture["kook_year"]
    assert engine.taishui() == fixture["taishui"]
    assert engine.ty() == fixture["ty"]
    assert engine.ty_gong() == fixture["ty_gong"]
    assert engine.skyyi() == fixture["skyyi"]
    assert engine.earthyi() == fixture["earthyi"]
    assert engine.fgd() == fixture["fgd"]
    assert engine.zhifu() == fixture["zhifu"]
    assert engine.skyeyes() == fixture["skyeyes"]
    assert engine.skyeyes_des() == fixture["skyeyes_des"]
    assert engine.sf() == fixture["sf"]
    assert engine.home_cal() == fixture["home_cal"]
    assert engine.home_general() == fixture["home_general"]
    assert engine.home_vgen() == fixture["home_vgen"]
    assert engine.away_cal() == fixture["away_cal"]
    assert engine.away_general() == fixture["away_general"]
    assert engine.away_vgen() == fixture["away_vgen"]
    assert engine.set_cal() == fixture["set_cal"]
    assert engine.hegod() == fixture["hegod"]
    assert engine.jigod() == fixture["jigod"]
    assert engine.se() == fixture["se"]
    assert engine.kingbase() == fixture["kingbase"]
    assert engine.officerbase() == fixture["officerbase"]
    assert engine.pplbase() == fixture["pplbase"]

    assert _wufu(acc) == fixture["wufu"]
    assert _kingfu(acc) == fixture["kingfu"]
    assert _taijun(acc) == fixture["taijun"]
    assert _flybird(acc) == fixture["flybird"]
    assert _threewind(acc) == fixture["threewind"]
    assert _fivewind(acc) == fixture["fivewind"]
    assert _eightwind(acc) == fixture["eightwind"]
    assert _bigyo(acc) == fixture["bigyo"]
    assert _smyo(acc) == fixture["smyo"]
    assert _yangjiu(lunar_year) == fixture["yangjiu"]
    assert _baliu(lunar_year) == fixture["baliu"]
