"""Parity tests for the 七政四余 政余格局 (guolaoMoira) engine.

``tests/fixtures/guolao_moira_oracle.json`` was generated by running horosa's own
``guolaoMoira.js`` (``buildLocalMoiraPatterns``) on synthetic charts with empty
``godRows`` and empty ``fixedStarSu28`` — i.e. exactly horosa's *offline* behaviour,
where the 神煞-dependent patterns (日月拱贵人/命登岁驾) and 近宿界 do not fire. The
FateBridge port must reproduce the pattern list (name + level, in order) byte-for-byte
for every case. Pure sign-index arithmetic → deterministic across Python 3.10–3.13.
"""

from __future__ import annotations

import json
from pathlib import Path

from fatebridge.core import guolao_moira

_FIXTURE = Path(__file__).resolve().parent / "fixtures" / "guolao_moira_oracle.json"
_CASES = json.loads(_FIXTURE.read_text(encoding="utf-8"))


def _names_levels(patterns):
    return [(p["name"], p["level"]) for p in patterns]


def test_oracle_fixture_is_nonempty():
    assert _CASES, "guolaoMoira oracle fixture must contain cases"


def test_matches_horosa_js_oracle():
    """Every case must match horosa's guolaoMoira.js pattern list exactly."""
    for case in _CASES:
        got = _names_levels(guolao_moira.calculate(case["facts"]))
        expected = [(p["name"], p["level"]) for p in case["expected"]]
        assert (
            got == expected
        ), f"mismatch on case: {case['label']}\n  got={got}\n  exp={expected}"


def test_good_patterns_sort_before_bad():
    """build order: good first, bad after (matches JS level sort)."""
    for case in _CASES:
        patterns = guolao_moira.calculate(case["facts"])
        ranks = [0 if p["level"] == "good" else 1 for p in patterns]
        assert ranks == sorted(ranks), case["label"]


def test_god_dependent_patterns_inert_without_gods():
    """日月拱贵人 / 命登岁驾 stay inert when 神煞 positions are absent (oracle cases)."""
    for case in _CASES:
        names = {p["name"] for p in guolao_moira.calculate(case["facts"])}
        assert "日月拱贵人" not in names
        assert "命登岁驾" not in names


def test_compute_god_signidx_guolao_qili():
    """《三命通会》起例锁：天贵(阳/昼)以年干、玉贵(阴/夜)以年干、岁驾(太岁)以年支；戌将盘映射。

    阳贵(昼/天贵) 甲加丑逆行：甲丑 乙子 丙亥 丁酉 戊丑 己申 庚未 辛午 壬巳 癸卯。
    阴贵(夜/玉贵) 甲加未顺行：甲未 乙申 丙酉 丁亥 戊未 己子 庚丑 辛寅 壬卯 癸巳。
    地支→星座序号：子10 丑9 寅8 卯7 辰6 巳5 午4 未3 申2 酉1 戌0 亥11。
    """
    # 庚辰（用户本命年柱）：天贵未(3)、玉贵丑(9)、岁驾辰(6)。
    assert guolao_moira.compute_god_signidx("庚", "辰") == {
        "天贵": 3,
        "玉贵": 9,
        "岁驾": 6,
    }
    # 甲子：天贵丑(9)、玉贵未(3)、岁驾子(10)。
    assert guolao_moira.compute_god_signidx("甲", "子") == {
        "天贵": 9,
        "玉贵": 3,
        "岁驾": 10,
    }
    # 癸亥：天贵卯(7)、玉贵巳(5)、岁驾亥(11)。
    assert guolao_moira.compute_god_signidx("癸", "亥") == {
        "天贵": 7,
        "玉贵": 5,
        "岁驾": 11,
    }


def test_purple_clouds_matches_horosa_fixtures():
    """紫炁(木余) horosa 对照锁：4 张 horosa 七政四余盘 fixture 的紫炁黄经，残差 <0.01°。"""
    # (JD_UT, horosa Purple Clouds 黄经) —— chart_guolao / 1998_predictive / liureng / traditional
    horosa_points = [
        (2446145.583333333, 358.66910331920116),
        (2450865.033333333, 164.80172577759032),
        (2461135.054166667, 166.32382978206476),
        (2461193.770833333, 168.39076),
    ]
    for jd, expected in horosa_points:
        got = guolao_moira.purple_clouds_longitude(jd)
        delta = ((got - expected + 180) % 360) - 180
        assert (
            abs(delta) < 0.01
        ), f"jd={jd}: 紫炁 {got} vs horosa {expected} (Δ={delta})"


def test_si_yu_sign_index_matches_horosa_chart():
    """四余(孛/罗/计/炁) horosa 对照锁：chart_guolao fixture(1985-03-21 10:00 +08 上海)。

    horosa 后端实测：孛 Aries(0)、罗 Taurus(1)、计 Scorpio(7)、炁 Pisces(11)。
    """
    from fatebridge.services.astrology import calculate_core_chart_analysis

    guolao = calculate_core_chart_analysis(
        birth_year=1985,
        birth_month=3,
        birth_day=21,
        birth_hour=10,
        birth_minute=0,
        birth_longitude=121.47,
        birth_latitude=31.22,
        chart_variant="guolao_chart",
        birth_timezone="Asia/Shanghai",
    )["guolao"]
    assert guolao["si_yu_sign_index"] == {"孛": 0, "罗": 1, "计": 7, "炁": 11}


def test_gu_yue_du_ming_counts_purple_clouds():
    """孤月独明：紫炁补齐后，同宫计数覆盖全 11 体——炁与月同宫应使月不再「独居」。"""
    base = {
        "日": 1,
        "月": 5,
        "水": 2,
        "金": 3,
        "火": 7,
        "木": 8,
        "土": 9,
        "孛": 10,
        "罗": 0,
        "计": 6,
    }
    # 月独居（炁不在月宫）→ 点亮
    alone = guolao_moira.calculate(
        {"asc_lon": 75, "planet_signidx": {**base, "炁": 4}, "is_day": False}
    )
    assert any(p["name"] == "孤月独明" for p in alone)
    # 炁与月同宫(5) → 月不再独居 → 不点亮
    with_qi = guolao_moira.calculate(
        {"asc_lon": 75, "planet_signidx": {**base, "炁": 5}, "is_day": False}
    )
    assert not any(p["name"] == "孤月独明" for p in with_qi)


def test_ming_zuo_liangqi_near_su_boundary():
    """命坐两歧 近宿界（FB 等分宿口径）：命度近宿界但不近宫界亦应点亮。"""
    # 等分宿界 1*(360/28)=12.857°；asc=12.9 近宿界(0.04°)，但 12.9 不近宫界(12.9°)。
    near_su = guolao_moira.calculate({"asc_lon": 12.9, "planet_signidx": {}})
    assert any(p["name"] == "命坐两歧" for p in near_su)
    # 远离宫界与宿界：命度居中（如 18° → 宫界 18°、宿界距 12.857/25.714 均 >1°）不点亮。
    clear = guolao_moira.calculate({"asc_lon": 18.0, "planet_signidx": {}})
    assert not any(p["name"] == "命坐两歧" for p in clear)


def test_god_patterns_fire_when_positions_supplied():
    """供入神煞位置时，日月拱贵人 / 命登岁驾 应能点亮（Phase 2a）。"""
    # 命登岁驾：命度(ASC)与岁驾同宫。
    dengsuijia = guolao_moira.calculate(
        {"asc_lon": 6 * 30 + 15, "planet_signidx": {}, "god_signidx": {"岁驾": 6}}
    )
    assert any(p["name"] == "命登岁驾" for p in dengsuijia)

    # 日月拱贵人（昼取天贵）：日=天贵+4、月=天贵-4。
    gongguiren = guolao_moira.calculate(
        {
            "asc_lon": 100,
            "planet_signidx": {"日": 4, "月": 8},
            "god_signidx": {"天贵": 0},
            "is_day": True,
        }
    )
    assert any(p["name"] == "日月拱贵人" for p in gongguiren)


def test_section_text_format():
    """build_section_text mirrors runGuolaoMoira: 喜格/忌格 lines, 名（detail）；-joined."""
    # multi-fire case is index 0
    patterns = guolao_moira.calculate(_CASES[0]["facts"])
    text = guolao_moira.build_section_text(patterns)
    lines = text.split("\n")
    assert lines[0].startswith("喜格：")
    assert lines[1].startswith("忌格：")
    assert "金水相涵" in lines[0]
    assert "孛犯太阳" in lines[1]
    assert "；" in lines[1]  # multiple 忌格 joined


def test_empty_chart_yields_no_patterns():
    """A chart with no usable positions produces empty 喜格/忌格 (not a crash)."""
    patterns = guolao_moira.calculate({"asc_lon": None, "planet_signidx": {}})
    assert patterns == []
    assert guolao_moira.build_section_text(patterns) == "喜格：（无）\n忌格：（无）"
