"""
Basic data structures and constants for BaZi calculations.
"""

from enum import Enum
from typing import Dict, Iterator, Mapping, NamedTuple, Optional, Tuple

# 天干 (Heavenly Stems)
HEAVENLY_STEMS = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"]

# 地支 (Earthly Branches)
EARTHLY_BRANCHES = [
    "子",
    "丑",
    "寅",
    "卯",
    "辰",
    "巳",
    "午",
    "未",
    "申",
    "酉",
    "戌",
    "亥",
]

# 紫微斗数宫位地支顺序：寅=0 起，顺数至丑=11。
ZIWEI_BRANCH_SEQUENCE = [
    "寅",
    "卯",
    "辰",
    "巳",
    "午",
    "未",
    "申",
    "酉",
    "戌",
    "亥",
    "子",
    "丑",
]


# 五行 (Five Elements)
class Element(Enum):
    WOOD = "木"  # 木
    FIRE = "火"  # 火
    EARTH = "土"  # 土
    METAL = "金"  # 金
    WATER = "水"  # 水


# 阴阳 (Yin Yang)
class Polarity(Enum):
    YANG = "阳"
    YIN = "阴"


# 天干对应的五行和阴阳
STEM_ELEMENTS = {
    "甲": (Element.WOOD, Polarity.YANG),
    "乙": (Element.WOOD, Polarity.YIN),
    "丙": (Element.FIRE, Polarity.YANG),
    "丁": (Element.FIRE, Polarity.YIN),
    "戊": (Element.EARTH, Polarity.YANG),
    "己": (Element.EARTH, Polarity.YIN),
    "庚": (Element.METAL, Polarity.YANG),
    "辛": (Element.METAL, Polarity.YIN),
    "壬": (Element.WATER, Polarity.YANG),
    "癸": (Element.WATER, Polarity.YIN),
}

# 地支对应的五行和阴阳
BRANCH_ELEMENTS = {
    "子": (Element.WATER, Polarity.YANG),
    "丑": (Element.EARTH, Polarity.YIN),
    "寅": (Element.WOOD, Polarity.YANG),
    "卯": (Element.WOOD, Polarity.YIN),
    "辰": (Element.EARTH, Polarity.YANG),
    "巳": (Element.FIRE, Polarity.YIN),
    "午": (Element.FIRE, Polarity.YANG),
    "未": (Element.EARTH, Polarity.YIN),
    "申": (Element.METAL, Polarity.YANG),
    "酉": (Element.METAL, Polarity.YIN),
    "戌": (Element.EARTH, Polarity.YANG),
    "亥": (Element.WATER, Polarity.YIN),
}

# 五行相生关系 (Generation Cycle)
GENERATION_CYCLE = {
    Element.WOOD: Element.FIRE,  # 木生火
    Element.FIRE: Element.EARTH,  # 火生土
    Element.EARTH: Element.METAL,  # 土生金
    Element.METAL: Element.WATER,  # 金生水
    Element.WATER: Element.WOOD,  # 水生木
}

# 五行相克关系 (Destruction Cycle)
DESTRUCTION_CYCLE = {
    Element.WOOD: Element.EARTH,  # 木克土
    Element.FIRE: Element.METAL,  # 火克金
    Element.EARTH: Element.WATER,  # 土克水
    Element.METAL: Element.WOOD,  # 金克木
    Element.WATER: Element.FIRE,  # 水克火
}

# 地支藏干 (Hidden Stems in Branches)
BRANCH_HIDDEN_STEMS = {
    "子": ["癸"],
    "丑": ["己", "癸", "辛"],
    "寅": ["甲", "丙", "戊"],
    "卯": ["乙"],
    "辰": ["戊", "乙", "癸"],
    "巳": ["丙", "庚", "戊"],
    "午": ["丁", "己"],
    "未": ["己", "丁", "乙"],
    "申": ["庚", "壬", "戊"],
    "酉": ["辛"],
    "戌": ["戊", "辛", "丁"],
    "亥": ["壬", "甲"],
}


def count_element_distribution(
    pillars: Mapping[str, Tuple[str, str]],
) -> Dict[Element, float]:
    """Weighted five-element tally over a pillar map.

    Standard 命局五行 weighting, identical across the career/health/wealth
    analyses it was extracted from: visible stem = 1.0, branch = 0.5, each
    hidden stem of the branch = 0.3. Returns a dict with every Element present
    (zero-initialised) so callers can index any element without a KeyError.
    """
    counts: Dict[Element, float] = {e: 0.0 for e in Element}
    for stem, branch in pillars.values():
        counts[STEM_ELEMENTS[stem][0]] += 1.0
        counts[BRANCH_ELEMENTS[branch][0]] += 0.5
        for hidden in BRANCH_HIDDEN_STEMS.get(branch, []):
            counts[STEM_ELEMENTS[hidden][0]] += 0.3
    return counts


# 十神 (Ten Gods) - relationships between day stem and other stems
class TenGod(Enum):
    COMPARE = "比肩"  # Same element, same polarity
    ROB_WEALTH = "劫财"  # Same element, different polarity
    FOOD_GOD = "食神"  # Generated by day stem, same polarity
    HURT_OFFICER = "伤官"  # Generated by day stem, different polarity
    POSITIVE_WEALTH = "正财"  # Destroyed by day stem, different polarity
    PARTIAL_WEALTH = "偏财"  # Destroyed by day stem, same polarity
    POSITIVE_OFFICER = "正官"  # Destroys day stem, different polarity
    SEVEN_KILLER = "七杀"  # Destroys day stem, same polarity
    POSITIVE_SEAL = "正印"  # Generates day stem, different polarity
    PARTIAL_SEAL = "偏印"  # Generates day stem, same polarity


def get_ten_god(day_stem: str, other_stem: str) -> TenGod:
    """Calculate the Ten God relationship between day stem and another stem."""
    day_element, day_polarity = STEM_ELEMENTS[day_stem]
    other_element, other_polarity = STEM_ELEMENTS[other_stem]

    if day_element == other_element:
        if day_polarity == other_polarity:
            return TenGod.COMPARE
        else:
            return TenGod.ROB_WEALTH
    elif GENERATION_CYCLE[day_element] == other_element:
        # Day stem generates other stem
        if day_polarity == other_polarity:
            return TenGod.FOOD_GOD
        else:
            return TenGod.HURT_OFFICER
    elif DESTRUCTION_CYCLE[day_element] == other_element:
        # Day stem destroys other stem
        if day_polarity == other_polarity:
            return TenGod.PARTIAL_WEALTH
        else:
            return TenGod.POSITIVE_WEALTH
    elif DESTRUCTION_CYCLE[other_element] == day_element:
        # Other stem destroys day stem
        if day_polarity == other_polarity:
            return TenGod.SEVEN_KILLER
        else:
            return TenGod.POSITIVE_OFFICER
    elif GENERATION_CYCLE[other_element] == day_element:
        # Other stem generates day stem
        if day_polarity == other_polarity:
            return TenGod.PARTIAL_SEAL
        else:
            return TenGod.POSITIVE_SEAL
    else:
        # This shouldn't happen with valid inputs
        raise ValueError(f"Invalid relationship between {day_stem} and {other_stem}")


# 月份地支对应表 (Month to Branch mapping)
# 说明：传统八字以节气为准；此表保留给无节气上下文时的兜底映射
MONTH_BRANCHES = {
    1: "丑",  # 一月 -> 丑月 (大寒-立春)
    2: "寅",  # 二月 -> 寅月 (立春-惊蛰)
    3: "卯",  # 三月 -> 卯月 (惊蛰-清明)
    4: "辰",  # 四月 -> 辰月 (清明-立夏)
    5: "巳",  # 五月 -> 巳月 (立夏-芒种)
    6: "午",  # 六月 -> 午月 (芒种-小暑)
    7: "未",  # 七月 -> 未月 (小暑-立秋)
    8: "申",  # 八月 -> 申月 (立秋-白露)
    9: "酉",  # 九月 -> 酉月 (白露-寒露)
    10: "戌",  # 十月 -> 戌月 (寒露-立冬)
    11: "亥",  # 十一月 -> 亥月 (立冬-大雪)
    12: "子",  # 十二月 -> 子月 (大雪-大寒)
}


def get_hour_branch(hour: int) -> str:
    """Get the earthly branch for a given hour (0-23)."""
    # 传统时辰划分（每个时辰2小时）：
    # 子时: 23:00-01:00, 丑时: 01:00-03:00, 寅时: 03:00-05:00, 卯时: 05:00-07:00
    # 辰时: 07:00-09:00, 巳时: 09:00-11:00, 午时: 11:00-13:00, 未时: 13:00-15:00
    # 申时: 15:00-17:00, 酉时: 17:00-19:00, 戌时: 19:00-21:00, 亥时: 21:00-23:00
    if hour == 23 or hour == 0:
        return "子"
    elif hour == 1 or hour == 2:
        return "丑"
    elif hour == 3 or hour == 4:
        return "寅"
    elif hour == 5 or hour == 6:
        return "卯"
    elif hour == 7 or hour == 8:
        return "辰"
    elif hour == 9 or hour == 10:
        return "巳"
    elif hour == 11 or hour == 12:
        return "午"
    elif hour == 13 or hour == 14:
        return "未"
    elif hour == 15 or hour == 16:
        return "申"
    elif hour == 17 or hour == 18:
        return "酉"
    elif hour == 19 or hour == 20:
        return "戌"
    elif hour == 21 or hour == 22:
        return "亥"
    else:
        raise ValueError(f"Invalid hour: {hour}")  # 这种情况不应该出现


# 纳音表 (Nayin Table) - 六十甲子纳音
NAYIN_TABLE = {
    # 甲子乙丑海中金
    ("甲", "子"): "海中金",
    ("乙", "丑"): "海中金",
    # 丙寅丁卯炉中火
    ("丙", "寅"): "炉中火",
    ("丁", "卯"): "炉中火",
    # 戊辰己巳大林木
    ("戊", "辰"): "大林木",
    ("己", "巳"): "大林木",
    # 庚午辛未路旁土
    ("庚", "午"): "路旁土",
    ("辛", "未"): "路旁土",
    # 壬申癸酉剑锋金
    ("壬", "申"): "剑锋金",
    ("癸", "酉"): "剑锋金",
    # 甲戌乙亥山头火
    ("甲", "戌"): "山头火",
    ("乙", "亥"): "山头火",
    # 丙子丁丑涧下水
    ("丙", "子"): "涧下水",
    ("丁", "丑"): "涧下水",
    # 戊寅己卯城墙土
    ("戊", "寅"): "城墙土",
    ("己", "卯"): "城墙土",
    # 庚辰辛巳白蜡金
    ("庚", "辰"): "白蜡金",
    ("辛", "巳"): "白蜡金",
    # 壬午癸未杨柳木
    ("壬", "午"): "杨柳木",
    ("癸", "未"): "杨柳木",
    # 甲申乙酉泉中水
    ("甲", "申"): "泉中水",
    ("乙", "酉"): "泉中水",
    # 丙戌丁亥屋上土
    ("丙", "戌"): "屋上土",
    ("丁", "亥"): "屋上土",
    # 戊子己丑霹雳火
    ("戊", "子"): "霹雳火",
    ("己", "丑"): "霹雳火",
    # 庚寅辛卯松柏木
    ("庚", "寅"): "松柏木",
    ("辛", "卯"): "松柏木",
    # 壬辰癸巳长流水
    ("壬", "辰"): "长流水",
    ("癸", "巳"): "长流水",
    # 甲午乙未沙中金
    ("甲", "午"): "沙中金",
    ("乙", "未"): "沙中金",
    # 丙申丁酉山下火
    ("丙", "申"): "山下火",
    ("丁", "酉"): "山下火",
    # 戊戌己亥平地木
    ("戊", "戌"): "平地木",
    ("己", "亥"): "平地木",
    # 庚子辛丑壁上土
    ("庚", "子"): "壁上土",
    ("辛", "丑"): "壁上土",
    # 壬寅癸卯金箔金
    ("壬", "寅"): "金箔金",
    ("癸", "卯"): "金箔金",
    # 甲辰乙巳覆灯火
    ("甲", "辰"): "覆灯火",
    ("乙", "巳"): "覆灯火",
    # 丙午丁未天河水
    ("丙", "午"): "天河水",
    ("丁", "未"): "天河水",
    # 戊申己酉大驿土
    ("戊", "申"): "大驿土",
    ("己", "酉"): "大驿土",
    # 庚戌辛亥钗钏金
    ("庚", "戌"): "钗钏金",
    ("辛", "亥"): "钗钏金",
    # 壬子癸丑桑柘木
    ("壬", "子"): "桑柘木",
    ("癸", "丑"): "桑柘木",
    # 甲寅乙卯大溪水
    ("甲", "寅"): "大溪水",
    ("乙", "卯"): "大溪水",
    # 丙辰丁巳沙中土
    ("丙", "辰"): "沙中土",
    ("丁", "巳"): "沙中土",
    # 戊午己未天上火
    ("戊", "午"): "天上火",
    ("己", "未"): "天上火",
    # 庚申辛酉石榴木
    ("庚", "申"): "石榴木",
    ("辛", "酉"): "石榴木",
    # 壬戌癸亥大海水
    ("壬", "戌"): "大海水",
    ("癸", "亥"): "大海水",
}


def get_nayin(stem: str, branch: str) -> str:
    """获取干支的纳音"""
    return NAYIN_TABLE.get((stem, branch), "未知纳音")


# 地支六冲关系
BRANCH_CONFLICTS = {
    "子": "午",
    "午": "子",  # 子午冲
    "丑": "未",
    "未": "丑",  # 丑未冲
    "寅": "申",
    "申": "寅",  # 寅申冲
    "卯": "酉",
    "酉": "卯",  # 卯酉冲
    "辰": "戌",
    "戌": "辰",  # 辰戌冲
    "巳": "亥",
    "亥": "巳",  # 巳亥冲
}

# 地支六合关系
BRANCH_COMBINATIONS = {
    "子": "丑",
    "丑": "子",  # 子丑合土
    "寅": "亥",
    "亥": "寅",  # 寅亥合木
    "卯": "戌",
    "戌": "卯",  # 卯戌合火
    "辰": "酉",
    "酉": "辰",  # 辰酉合金
    "巳": "申",
    "申": "巳",  # 巳申合水
    "午": "未",
    "未": "午",  # 午未合土
}

# 地支三合关系
BRANCH_TRIPLE_COMBINATIONS = {
    "申子辰": "水局",  # 申子辰三合水局
    "亥卯未": "木局",  # 亥卯未三合木局
    "寅午戌": "火局",  # 寅午戌三合火局
    "巳酉丑": "金局",  # 巳酉丑三合金局
}

# 地支六害关系（穿）
BRANCH_HARMS = {
    "子": "未",
    "未": "子",  # 子未害
    "丑": "午",
    "午": "丑",  # 丑午害
    "寅": "巳",
    "巳": "寅",  # 寅巳害
    "卯": "辰",
    "辰": "卯",  # 卯辰害
    "申": "亥",
    "亥": "申",  # 申亥害
    "酉": "戌",
    "戌": "酉",  # 酉戌害
}

# 地支三刑关系。每组互刑：
#   寅巳申（无恩之刑）、丑戌未（恃势之刑）、子卯（无礼之刑，互刑）
BRANCH_THREE_PUNISHMENTS = (
    ("寅", "巳", "申"),
    ("丑", "戌", "未"),
    ("子", "卯"),
)
# 自刑地支（同支重见为刑）
BRANCH_SELF_PUNISHMENTS = frozenset({"辰", "午", "酉", "亥"})

# 地支三会方局（同方位三支聚气，力量最强）
BRANCH_SEASONAL_COMBINATIONS = {
    "寅卯辰": "木局",  # 东方木
    "巳午未": "火局",  # 南方火
    "申酉戌": "金局",  # 西方金
    "亥子丑": "水局",  # 北方水
}

# 局名 → 五行（供三合 / 三会计分复用，避免重复解析 "水局" 字符串）
BUREAU_ELEMENT = {
    "水局": Element.WATER,
    "木局": Element.WOOD,
    "火局": Element.FIRE,
    "金局": Element.METAL,
    "土局": Element.EARTH,
}

# 六合化气：地支对（frozenset）→ 化神五行。
# 午未合化土沿用本仓 BRANCH_COMBINATIONS 注释的既定取向（午未合土）。
BRANCH_COMBINATION_ELEMENT = {
    frozenset({"子", "丑"}): Element.EARTH,
    frozenset({"寅", "亥"}): Element.WOOD,
    frozenset({"卯", "戌"}): Element.FIRE,
    frozenset({"辰", "酉"}): Element.METAL,
    frozenset({"巳", "申"}): Element.WATER,
    frozenset({"午", "未"}): Element.EARTH,
}

# 三合局旺神（中神）。半合须含旺神方成立：旺+生 或 旺+库。
TRIPLE_COMBINATION_PEAK = {
    "申子辰": "子",
    "亥卯未": "卯",
    "寅午戌": "午",
    "巳酉丑": "酉",
}

# 十神关系映射（用于快速查找）
SHISHEN_RELATIONS = {
    ("甲", "甲"): "比肩",
    ("甲", "乙"): "劫财",
    ("甲", "丙"): "食神",
    ("甲", "丁"): "伤官",
    ("甲", "戊"): "偏财",
    ("甲", "己"): "正财",
    ("甲", "庚"): "七杀",
    ("甲", "辛"): "正官",
    ("甲", "壬"): "偏印",
    ("甲", "癸"): "正印",
    ("乙", "甲"): "劫财",
    ("乙", "乙"): "比肩",
    ("乙", "丙"): "伤官",
    ("乙", "丁"): "食神",
    ("乙", "戊"): "正财",
    ("乙", "己"): "偏财",
    ("乙", "庚"): "正官",
    ("乙", "辛"): "七杀",
    ("乙", "壬"): "正印",
    ("乙", "癸"): "偏印",
    ("丙", "甲"): "偏印",
    ("丙", "乙"): "正印",
    ("丙", "丙"): "比肩",
    ("丙", "丁"): "劫财",
    ("丙", "戊"): "食神",
    ("丙", "己"): "伤官",
    ("丙", "庚"): "偏财",
    ("丙", "辛"): "正财",
    ("丙", "壬"): "七杀",
    ("丙", "癸"): "正官",
    ("丁", "甲"): "正印",
    ("丁", "乙"): "偏印",
    ("丁", "丙"): "劫财",
    ("丁", "丁"): "比肩",
    ("丁", "戊"): "伤官",
    ("丁", "己"): "食神",
    ("丁", "庚"): "正财",
    ("丁", "辛"): "偏财",
    ("丁", "壬"): "正官",
    ("丁", "癸"): "七杀",
    ("戊", "甲"): "七杀",
    ("戊", "乙"): "正官",
    ("戊", "丙"): "偏印",
    ("戊", "丁"): "正印",
    ("戊", "戊"): "比肩",
    ("戊", "己"): "劫财",
    ("戊", "庚"): "食神",
    ("戊", "辛"): "伤官",
    ("戊", "壬"): "偏财",
    ("戊", "癸"): "正财",
    ("己", "甲"): "正官",
    ("己", "乙"): "七杀",
    ("己", "丙"): "正印",
    ("己", "丁"): "偏印",
    ("己", "戊"): "劫财",
    ("己", "己"): "比肩",
    ("己", "庚"): "伤官",
    ("己", "辛"): "食神",
    ("己", "壬"): "正财",
    ("己", "癸"): "偏财",
    ("庚", "甲"): "偏财",
    ("庚", "乙"): "正财",
    ("庚", "丙"): "七杀",
    ("庚", "丁"): "正官",
    ("庚", "戊"): "偏印",
    ("庚", "己"): "正印",
    ("庚", "庚"): "比肩",
    ("庚", "辛"): "劫财",
    ("庚", "壬"): "食神",
    ("庚", "癸"): "伤官",
    ("辛", "甲"): "正财",
    ("辛", "乙"): "偏财",
    ("辛", "丙"): "正官",
    ("辛", "丁"): "七杀",
    ("辛", "戊"): "正印",
    ("辛", "己"): "偏印",
    ("辛", "庚"): "劫财",
    ("辛", "辛"): "比肩",
    ("辛", "壬"): "伤官",
    ("辛", "癸"): "食神",
    ("壬", "甲"): "食神",
    ("壬", "乙"): "伤官",
    ("壬", "丙"): "偏财",
    ("壬", "丁"): "正财",
    ("壬", "戊"): "七杀",
    ("壬", "己"): "正官",
    ("壬", "庚"): "偏印",
    ("壬", "辛"): "正印",
    ("壬", "壬"): "比肩",
    ("壬", "癸"): "劫财",
    ("癸", "甲"): "伤官",
    ("癸", "乙"): "食神",
    ("癸", "丙"): "正财",
    ("癸", "丁"): "偏财",
    ("癸", "戊"): "正官",
    ("癸", "己"): "七杀",
    ("癸", "庚"): "正印",
    ("癸", "辛"): "偏印",
    ("癸", "壬"): "劫财",
    ("癸", "癸"): "比肩",
}


def get_shishen(day_stem: str, other_stem: str) -> str:
    """获取十神关系"""
    return SHISHEN_RELATIONS.get((day_stem, other_stem), "未知")


def check_branch_conflict(branch1: str, branch2: str) -> bool:
    """检查地支是否相冲"""
    return BRANCH_CONFLICTS.get(branch1) == branch2


def check_branch_combination(branch1: str, branch2: str) -> bool:
    """检查地支是否六合"""
    return BRANCH_COMBINATIONS.get(branch1) == branch2


# 性别归一化 (Gender normalization)
# 多个分析模块（子女 / 桃花 / 婚姻 / 生命维度）此前各自复制同一套 token 集合与
# 归一化逻辑，这里集中为单一信源。
GENDER_MALE_TOKENS = frozenset({"male", "m", "男", "man"})
GENDER_FEMALE_TOKENS = frozenset({"female", "f", "女", "woman"})


def normalize_gender(gender: Optional[str]) -> Optional[str]:
    """将自由格式的性别输入归一化为 ``"male"`` / ``"female"`` / ``None``。

    None、空串、无法识别的取值统一返回 None（中性，由各模块自行决定如何处理）。
    """
    if gender is None:
        return None
    token = gender.strip().lower()
    if token in GENDER_MALE_TOKENS:
        return "male"
    if token in GENDER_FEMALE_TOKENS:
        return "female"
    return None


# 十神扫描原语 (Ten-god scan primitive)
# 各维度分析此前都手写同一段"遍历四柱天干 + 地支藏干，用 get_ten_god 归类、天干计 1.0
# 地支藏干计 0.5"的循环，但归类方式各异（直方图 / 过滤定位 / 分桶 / 计权）。这里抽出
# 一个**低层迭代器**，由各调用方自行过滤、塑形——而不是一个无所不包的大函数。
#
# 关键差异由 ``skip_day_pillar`` 表达：
#   - career / marriage 跳过**整个日柱**（连日支藏干也不计）；
#   - personality / wealth / education / relatives / children 仅跳过**日干本身**，
#     仍计入日支藏干。
# 两类共同点：日干自身从不计入（它对自身是比肩，无分析意义）。
# 与原循环一致，本原语**不吞** get_ten_god 抛出的异常（仅 life_dimensions 另行吞错，
# 故不迁移它）。


class PillarGod(NamedTuple):
    """四柱扫描中的单个十神条目（一个天干，或一个地支藏干）。"""

    pillar: str  # 柱位 key：year / month / day / hour（或胎元等）
    branch: str  # 该柱的地支（天干条目与藏干条目都携带所属柱的地支）
    location: str  # "天干" 或 "地支藏干"
    char: str  # 被归类的天干字（藏干时为藏干天干）
    ten_god: TenGod  # 相对日干的十神
    weight: float  # 天干 1.0，地支藏干 0.5


def iter_pillar_gods(
    pillars: Mapping[str, Tuple[str, str]],
    day_stem: str,
    *,
    skip_day_pillar: bool = False,
    stem_weight: float = 1.0,
    hidden_weight: float = 0.5,
) -> Iterator[PillarGod]:
    """遍历四柱，逐个产出天干与地支藏干的十神条目。

    Args:
        pillars: 四柱 ``{label: (stem, branch)}``，须含 ``"day"`` 柱。
        day_stem: 日主天干（取十神的基准）。
        skip_day_pillar: True 则跳过整个日柱（career / marriage）；
            False（默认）跳过日干本身但仍计入日支藏干。
        stem_weight / hidden_weight: 天干 / 地支藏干的计权，默认 1.0 / 0.5。
    """
    for pillar, (stem, branch) in pillars.items():
        is_day = pillar == "day"
        if is_day and skip_day_pillar:
            continue
        if not is_day:
            yield PillarGod(
                pillar, branch, "天干", stem, get_ten_god(day_stem, stem), stem_weight
            )
        for hidden in BRANCH_HIDDEN_STEMS.get(branch, []):
            yield PillarGod(
                pillar,
                branch,
                "地支藏干",
                hidden,
                get_ten_god(day_stem, hidden),
                hidden_weight,
            )


def count_ten_gods(
    pillars: Mapping[str, Tuple[str, str]],
    day_stem: str,
    *,
    skip_day_pillar: bool = False,
) -> Dict[TenGod, float]:
    """汇总四柱十神直方图（含全部十神 key，未出现者为 0.0）。

    用于只需"各十神总权重"的调用方（如 career / personality）。
    """
    counts: Dict[TenGod, float] = {tg: 0.0 for tg in TenGod}
    for entry in iter_pillar_gods(pillars, day_stem, skip_day_pillar=skip_day_pillar):
        counts[entry.ten_god] += entry.weight
    return counts


def sum_ten_god_weight(
    pillars: Mapping[str, Tuple[str, str]],
    day_stem: str,
    gods: Tuple[TenGod, ...],
) -> float:
    """汇总某一组十神的总权重（四柱天干 + 地支藏干），保留 1 位小数。

    各维度分析里反复出现的「某类星力量」原语：把 :func:`iter_pillar_gods`
    的逐条权重按所选十神集合求和。用于只关心单一星组合力的调用方
    （relatives 父母星、romance 异性缘星、education 各学业星等）。
    """
    return round(
        sum(
            entry.weight
            for entry in iter_pillar_gods(pillars, day_stem)
            if entry.ten_god in gods
        ),
        1,
    )
