"""
Basic data structures and constants for BaZi calculations.
"""

from typing import Optional
from enum import Enum

# 天干 (Heavenly Stems)
HEAVENLY_STEMS = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"]

# 地支 (Earthly Branches)
EARTHLY_BRANCHES = [
    "子",
    "丑",
    "寅",
    "卯",
    "辰",
    "巳",
    "午",
    "未",
    "申",
    "酉",
    "戌",
    "亥",
]


# 五行 (Five Elements)
class Element(Enum):
    WOOD = "木"  # 木
    FIRE = "火"  # 火
    EARTH = "土"  # 土
    METAL = "金"  # 金
    WATER = "水"  # 水


# 阴阳 (Yin Yang)
class Polarity(Enum):
    YANG = "阳"
    YIN = "阴"


# 天干对应的五行和阴阳
STEM_ELEMENTS = {
    "甲": (Element.WOOD, Polarity.YANG),
    "乙": (Element.WOOD, Polarity.YIN),
    "丙": (Element.FIRE, Polarity.YANG),
    "丁": (Element.FIRE, Polarity.YIN),
    "戊": (Element.EARTH, Polarity.YANG),
    "己": (Element.EARTH, Polarity.YIN),
    "庚": (Element.METAL, Polarity.YANG),
    "辛": (Element.METAL, Polarity.YIN),
    "壬": (Element.WATER, Polarity.YANG),
    "癸": (Element.WATER, Polarity.YIN),
}

# 地支对应的五行和阴阳
BRANCH_ELEMENTS = {
    "子": (Element.WATER, Polarity.YANG),
    "丑": (Element.EARTH, Polarity.YIN),
    "寅": (Element.WOOD, Polarity.YANG),
    "卯": (Element.WOOD, Polarity.YIN),
    "辰": (Element.EARTH, Polarity.YANG),
    "巳": (Element.FIRE, Polarity.YIN),
    "午": (Element.FIRE, Polarity.YANG),
    "未": (Element.EARTH, Polarity.YIN),
    "申": (Element.METAL, Polarity.YANG),
    "酉": (Element.METAL, Polarity.YIN),
    "戌": (Element.EARTH, Polarity.YANG),
    "亥": (Element.WATER, Polarity.YIN),
}

# 五行相生关系 (Generation Cycle)
GENERATION_CYCLE = {
    Element.WOOD: Element.FIRE,  # 木生火
    Element.FIRE: Element.EARTH,  # 火生土
    Element.EARTH: Element.METAL,  # 土生金
    Element.METAL: Element.WATER,  # 金生水
    Element.WATER: Element.WOOD,  # 水生木
}

# 五行相克关系 (Destruction Cycle)
DESTRUCTION_CYCLE = {
    Element.WOOD: Element.EARTH,  # 木克土
    Element.FIRE: Element.METAL,  # 火克金
    Element.EARTH: Element.WATER,  # 土克水
    Element.METAL: Element.WOOD,  # 金克木
    Element.WATER: Element.FIRE,  # 水克火
}

# 地支藏干 (Hidden Stems in Branches)
BRANCH_HIDDEN_STEMS = {
    "子": ["癸"],
    "丑": ["己", "癸", "辛"],
    "寅": ["甲", "丙", "戊"],
    "卯": ["乙"],
    "辰": ["戊", "乙", "癸"],
    "巳": ["丙", "庚", "戊"],
    "午": ["丁", "己"],
    "未": ["己", "丁", "乙"],
    "申": ["庚", "壬", "戊"],
    "酉": ["辛"],
    "戌": ["戊", "辛", "丁"],
    "亥": ["壬", "甲"],
}


# 十神 (Ten Gods) - relationships between day stem and other stems
class TenGod(Enum):
    COMPARE = "比肩"  # Same element, same polarity
    ROB_WEALTH = "劫财"  # Same element, different polarity
    FOOD_GOD = "食神"  # Generated by day stem, same polarity
    HURT_OFFICER = "伤官"  # Generated by day stem, different polarity
    POSITIVE_WEALTH = "正财"  # Destroyed by day stem, different polarity
    PARTIAL_WEALTH = "偏财"  # Destroyed by day stem, same polarity
    POSITIVE_OFFICER = "正官"  # Destroys day stem, different polarity
    SEVEN_KILLER = "七杀"  # Destroys day stem, same polarity
    POSITIVE_SEAL = "正印"  # Generates day stem, different polarity
    PARTIAL_SEAL = "偏印"  # Generates day stem, same polarity


def get_ten_god(day_stem: str, other_stem: str) -> TenGod:
    """Calculate the Ten God relationship between day stem and another stem."""
    day_element, day_polarity = STEM_ELEMENTS[day_stem]
    other_element, other_polarity = STEM_ELEMENTS[other_stem]

    if day_element == other_element:
        if day_polarity == other_polarity:
            return TenGod.COMPARE
        else:
            return TenGod.ROB_WEALTH
    elif GENERATION_CYCLE[day_element] == other_element:
        # Day stem generates other stem
        if day_polarity == other_polarity:
            return TenGod.FOOD_GOD
        else:
            return TenGod.HURT_OFFICER
    elif DESTRUCTION_CYCLE[day_element] == other_element:
        # Day stem destroys other stem
        if day_polarity == other_polarity:
            return TenGod.PARTIAL_WEALTH
        else:
            return TenGod.POSITIVE_WEALTH
    elif DESTRUCTION_CYCLE[other_element] == day_element:
        # Other stem destroys day stem
        if day_polarity == other_polarity:
            return TenGod.SEVEN_KILLER
        else:
            return TenGod.POSITIVE_OFFICER
    elif GENERATION_CYCLE[other_element] == day_element:
        # Other stem generates day stem
        if day_polarity == other_polarity:
            return TenGod.PARTIAL_SEAL
        else:
            return TenGod.POSITIVE_SEAL
    else:
        # This shouldn't happen with valid inputs
        raise ValueError(f"Invalid relationship between {day_stem} and {other_stem}")


# 月份地支对应表 (Month to Branch mapping)
# 说明：传统八字以节气为准；此表保留给无节气上下文时的兜底映射
MONTH_BRANCHES = {
    1: "丑",  # 一月 -> 丑月 (大寒-立春)
    2: "寅",  # 二月 -> 寅月 (立春-惊蛰)
    3: "卯",  # 三月 -> 卯月 (惊蛰-清明)
    4: "辰",  # 四月 -> 辰月 (清明-立夏)
    5: "巳",  # 五月 -> 巳月 (立夏-芒种)
    6: "午",  # 六月 -> 午月 (芒种-小暑)
    7: "未",  # 七月 -> 未月 (小暑-立秋)
    8: "申",  # 八月 -> 申月 (立秋-白露)
    9: "酉",  # 九月 -> 酉月 (白露-寒露)
    10: "戌",  # 十月 -> 戌月 (寒露-立冬)
    11: "亥",  # 十一月 -> 亥月 (立冬-大雪)
    12: "子",  # 十二月 -> 子月 (大雪-大寒)
}

# 时辰地支对应表 (Hour to Branch mapping)
HOUR_BRANCHES = {
    23: "子",
    1: "丑",
    3: "寅",
    5: "卯",
    7: "辰",
    9: "巳",
    11: "午",
    13: "未",
    15: "申",
    17: "酉",
    19: "戌",
    21: "亥",
}


def get_hour_branch(hour: int) -> str:
    """Get the earthly branch for a given hour (0-23)."""
    # 传统时辰划分（每个时辰2小时）：
    # 子时: 23:00-01:00, 丑时: 01:00-03:00, 寅时: 03:00-05:00, 卯时: 05:00-07:00
    # 辰时: 07:00-09:00, 巳时: 09:00-11:00, 午时: 11:00-13:00, 未时: 13:00-15:00
    # 申时: 15:00-17:00, 酉时: 17:00-19:00, 戌时: 19:00-21:00, 亥时: 21:00-23:00
    if hour == 23 or hour == 0:
        return "子"
    elif hour == 1 or hour == 2:
        return "丑"
    elif hour == 3 or hour == 4:
        return "寅"
    elif hour == 5 or hour == 6:
        return "卯"
    elif hour == 7 or hour == 8:
        return "辰"
    elif hour == 9 or hour == 10:
        return "巳"
    elif hour == 11 or hour == 12:
        return "午"
    elif hour == 13 or hour == 14:
        return "未"
    elif hour == 15 or hour == 16:
        return "申"
    elif hour == 17 or hour == 18:
        return "酉"
    elif hour == 19 or hour == 20:
        return "戌"
    elif hour == 21 or hour == 22:
        return "亥"
    else:
        raise ValueError(f"Invalid hour: {hour}")  # 这种情况不应该出现


# 纳音表 (Nayin Table) - 六十甲子纳音
NAYIN_TABLE = {
    # 甲子乙丑海中金
    ("甲", "子"): "海中金",
    ("乙", "丑"): "海中金",
    # 丙寅丁卯炉中火
    ("丙", "寅"): "炉中火",
    ("丁", "卯"): "炉中火",
    # 戊辰己巳大林木
    ("戊", "辰"): "大林木",
    ("己", "巳"): "大林木",
    # 庚午辛未路旁土
    ("庚", "午"): "路旁土",
    ("辛", "未"): "路旁土",
    # 壬申癸酉剑锋金
    ("壬", "申"): "剑锋金",
    ("癸", "酉"): "剑锋金",
    # 甲戌乙亥山头火
    ("甲", "戌"): "山头火",
    ("乙", "亥"): "山头火",
    # 丙子丁丑涧下水
    ("丙", "子"): "涧下水",
    ("丁", "丑"): "涧下水",
    # 戊寅己卯城墙土
    ("戊", "寅"): "城墙土",
    ("己", "卯"): "城墙土",
    # 庚辰辛巳白蜡金
    ("庚", "辰"): "白蜡金",
    ("辛", "巳"): "白蜡金",
    # 壬午癸未杨柳木
    ("壬", "午"): "杨柳木",
    ("癸", "未"): "杨柳木",
    # 甲申乙酉泉中水
    ("甲", "申"): "泉中水",
    ("乙", "酉"): "泉中水",
    # 丙戌丁亥屋上土
    ("丙", "戌"): "屋上土",
    ("丁", "亥"): "屋上土",
    # 戊子己丑霹雳火
    ("戊", "子"): "霹雳火",
    ("己", "丑"): "霹雳火",
    # 庚寅辛卯松柏木
    ("庚", "寅"): "松柏木",
    ("辛", "卯"): "松柏木",
    # 壬辰癸巳长流水
    ("壬", "辰"): "长流水",
    ("癸", "巳"): "长流水",
    # 甲午乙未沙中金
    ("甲", "午"): "沙中金",
    ("乙", "未"): "沙中金",
    # 丙申丁酉山下火
    ("丙", "申"): "山下火",
    ("丁", "酉"): "山下火",
    # 戊戌己亥平地木
    ("戊", "戌"): "平地木",
    ("己", "亥"): "平地木",
    # 庚子辛丑壁上土
    ("庚", "子"): "壁上土",
    ("辛", "丑"): "壁上土",
    # 壬寅癸卯金箔金
    ("壬", "寅"): "金箔金",
    ("癸", "卯"): "金箔金",
    # 甲辰乙巳覆灯火
    ("甲", "辰"): "覆灯火",
    ("乙", "巳"): "覆灯火",
    # 丙午丁未天河水
    ("丙", "午"): "天河水",
    ("丁", "未"): "天河水",
    # 戊申己酉大驿土
    ("戊", "申"): "大驿土",
    ("己", "酉"): "大驿土",
    # 庚戌辛亥钗钏金
    ("庚", "戌"): "钗钏金",
    ("辛", "亥"): "钗钏金",
    # 壬子癸丑桑柘木
    ("壬", "子"): "桑柘木",
    ("癸", "丑"): "桑柘木",
    # 甲寅乙卯大溪水
    ("甲", "寅"): "大溪水",
    ("乙", "卯"): "大溪水",
    # 丙辰丁巳沙中土
    ("丙", "辰"): "沙中土",
    ("丁", "巳"): "沙中土",
    # 戊午己未天上火
    ("戊", "午"): "天上火",
    ("己", "未"): "天上火",
    # 庚申辛酉石榴木
    ("庚", "申"): "石榴木",
    ("辛", "酉"): "石榴木",
    # 壬戌癸亥大海水
    ("壬", "戌"): "大海水",
    ("癸", "亥"): "大海水",
}


def get_nayin(stem: str, branch: str) -> str:
    """获取干支的纳音"""
    return NAYIN_TABLE.get((stem, branch), "未知纳音")


# 地支六冲关系
BRANCH_CONFLICTS = {
    "子": "午",
    "午": "子",  # 子午冲
    "丑": "未",
    "未": "丑",  # 丑未冲
    "寅": "申",
    "申": "寅",  # 寅申冲
    "卯": "酉",
    "酉": "卯",  # 卯酉冲
    "辰": "戌",
    "戌": "辰",  # 辰戌冲
    "巳": "亥",
    "亥": "巳",  # 巳亥冲
}

# 地支六合关系
BRANCH_COMBINATIONS = {
    "子": "丑",
    "丑": "子",  # 子丑合土
    "寅": "亥",
    "亥": "寅",  # 寅亥合木
    "卯": "戌",
    "戌": "卯",  # 卯戌合火
    "辰": "酉",
    "酉": "辰",  # 辰酉合金
    "巳": "申",
    "申": "巳",  # 巳申合水
    "午": "未",
    "未": "午",  # 午未合土
}

# 地支三合关系
BRANCH_TRIPLE_COMBINATIONS = {
    "申子辰": "水局",  # 申子辰三合水局
    "亥卯未": "木局",  # 亥卯未三合木局
    "寅午戌": "火局",  # 寅午戌三合火局
    "巳酉丑": "金局",  # 巳酉丑三合金局
}

# 十神关系映射（用于快速查找）
SHISHEN_RELATIONS = {
    ("甲", "甲"): "比肩",
    ("甲", "乙"): "劫财",
    ("甲", "丙"): "食神",
    ("甲", "丁"): "伤官",
    ("甲", "戊"): "偏财",
    ("甲", "己"): "正财",
    ("甲", "庚"): "七杀",
    ("甲", "辛"): "正官",
    ("甲", "壬"): "偏印",
    ("甲", "癸"): "正印",
    ("乙", "甲"): "劫财",
    ("乙", "乙"): "比肩",
    ("乙", "丙"): "伤官",
    ("乙", "丁"): "食神",
    ("乙", "戊"): "正财",
    ("乙", "己"): "偏财",
    ("乙", "庚"): "正官",
    ("乙", "辛"): "七杀",
    ("乙", "壬"): "正印",
    ("乙", "癸"): "偏印",
    ("丙", "甲"): "偏印",
    ("丙", "乙"): "正印",
    ("丙", "丙"): "比肩",
    ("丙", "丁"): "劫财",
    ("丙", "戊"): "食神",
    ("丙", "己"): "伤官",
    ("丙", "庚"): "偏财",
    ("丙", "辛"): "正财",
    ("丙", "壬"): "七杀",
    ("丙", "癸"): "正官",
    ("丁", "甲"): "正印",
    ("丁", "乙"): "偏印",
    ("丁", "丙"): "劫财",
    ("丁", "丁"): "比肩",
    ("丁", "戊"): "伤官",
    ("丁", "己"): "食神",
    ("丁", "庚"): "正财",
    ("丁", "辛"): "偏财",
    ("丁", "壬"): "正官",
    ("丁", "癸"): "七杀",
    ("戊", "甲"): "七杀",
    ("戊", "乙"): "正官",
    ("戊", "丙"): "偏印",
    ("戊", "丁"): "正印",
    ("戊", "戊"): "比肩",
    ("戊", "己"): "劫财",
    ("戊", "庚"): "食神",
    ("戊", "辛"): "伤官",
    ("戊", "壬"): "偏财",
    ("戊", "癸"): "正财",
    ("己", "甲"): "正官",
    ("己", "乙"): "七杀",
    ("己", "丙"): "正印",
    ("己", "丁"): "偏印",
    ("己", "戊"): "劫财",
    ("己", "己"): "比肩",
    ("己", "庚"): "伤官",
    ("己", "辛"): "食神",
    ("己", "壬"): "正财",
    ("己", "癸"): "偏财",
    ("庚", "甲"): "偏财",
    ("庚", "乙"): "正财",
    ("庚", "丙"): "七杀",
    ("庚", "丁"): "正官",
    ("庚", "戊"): "偏印",
    ("庚", "己"): "正印",
    ("庚", "庚"): "比肩",
    ("庚", "辛"): "劫财",
    ("庚", "壬"): "食神",
    ("庚", "癸"): "伤官",
    ("辛", "甲"): "正财",
    ("辛", "乙"): "偏财",
    ("辛", "丙"): "正官",
    ("辛", "丁"): "七杀",
    ("辛", "戊"): "正印",
    ("辛", "己"): "偏印",
    ("辛", "庚"): "劫财",
    ("辛", "辛"): "比肩",
    ("辛", "壬"): "伤官",
    ("辛", "癸"): "食神",
    ("壬", "甲"): "食神",
    ("壬", "乙"): "伤官",
    ("壬", "丙"): "偏财",
    ("壬", "丁"): "正财",
    ("壬", "戊"): "七杀",
    ("壬", "己"): "正官",
    ("壬", "庚"): "偏印",
    ("壬", "辛"): "正印",
    ("壬", "壬"): "比肩",
    ("壬", "癸"): "劫财",
    ("癸", "甲"): "伤官",
    ("癸", "乙"): "食神",
    ("癸", "丙"): "正财",
    ("癸", "丁"): "偏财",
    ("癸", "戊"): "正官",
    ("癸", "己"): "七杀",
    ("癸", "庚"): "正印",
    ("癸", "辛"): "偏印",
    ("癸", "壬"): "劫财",
    ("癸", "癸"): "比肩",
}


def get_shishen(day_stem: str, other_stem: str) -> str:
    """获取十神关系"""
    return SHISHEN_RELATIONS.get((day_stem, other_stem), "未知")


def check_branch_conflict(branch1: str, branch2: str) -> bool:
    """检查地支是否相冲"""
    return BRANCH_CONFLICTS.get(branch1) == branch2


def check_branch_combination(branch1: str, branch2: str) -> bool:
    """检查地支是否六合"""
    return BRANCH_COMBINATIONS.get(branch1) == branch2


def check_triple_combination(branch1: str, branch2: str, branch3: str) -> Optional[str]:
    """检查地支是否三合，返回三合局类型"""
    branches = sorted([branch1, branch2, branch3])

    for triple_key, bureau_type in BRANCH_TRIPLE_COMBINATIONS.items():
        if sorted(list(triple_key)) == branches:
            return bureau_type
    return None
